// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: proto/random-number-gen/v1/service.proto

package random_number_gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateIntRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LowBorder     int64                  `protobuf:"varint,1,opt,name=LowBorder,proto3" json:"LowBorder,omitempty"`
	HighBorder    int64                  `protobuf:"varint,2,opt,name=HighBorder,proto3" json:"HighBorder,omitempty"`
	Flag          *int32                 `protobuf:"varint,4,opt,name=flag,proto3,oneof" json:"flag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateIntRequest) Reset() {
	*x = GenerateIntRequest{}
	mi := &file_proto_random_number_gen_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateIntRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateIntRequest) ProtoMessage() {}

func (x *GenerateIntRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_random_number_gen_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateIntRequest.ProtoReflect.Descriptor instead.
func (*GenerateIntRequest) Descriptor() ([]byte, []int) {
	return file_proto_random_number_gen_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateIntRequest) GetLowBorder() int64 {
	if x != nil {
		return x.LowBorder
	}
	return 0
}

func (x *GenerateIntRequest) GetHighBorder() int64 {
	if x != nil {
		return x.HighBorder
	}
	return 0
}

func (x *GenerateIntRequest) GetFlag() int32 {
	if x != nil && x.Flag != nil {
		return *x.Flag
	}
	return 0
}

type GenerateIntResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int64                  `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateIntResponse) Reset() {
	*x = GenerateIntResponse{}
	mi := &file_proto_random_number_gen_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateIntResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateIntResponse) ProtoMessage() {}

func (x *GenerateIntResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_random_number_gen_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateIntResponse.ProtoReflect.Descriptor instead.
func (*GenerateIntResponse) Descriptor() ([]byte, []int) {
	return file_proto_random_number_gen_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateIntResponse) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_proto_random_number_gen_v1_service_proto protoreflect.FileDescriptor

const file_proto_random_number_gen_v1_service_proto_rawDesc = "" +
	"\n" +
	"(proto/random-number-gen/v1/service.proto\x12\x11random_number_gen\"z\n" +
	"\x12GenerateIntRequest\x12\x1c\n" +
	"\tLowBorder\x18\x01 \x01(\x03R\tLowBorder\x12\x1e\n" +
	"\n" +
	"HighBorder\x18\x02 \x01(\x03R\n" +
	"HighBorder\x12\x17\n" +
	"\x04flag\x18\x04 \x01(\x05H\x00R\x04flag\x88\x01\x01B\a\n" +
	"\x05_flagJ\x04\b\x03\x10\x04\"-\n" +
	"\x13GenerateIntResponse\x12\x16\n" +
	"\x06Result\x18\x01 \x01(\x03R\x06Result2o\n" +
	"\x0fRandomNumberGen\x12\\\n" +
	"\vGenerateInt\x12%.random_number_gen.GenerateIntRequest\x1a&.random_number_gen.GenerateIntResponseB.Z,proto/random-number-gen/v1;random_number_genb\x06proto3"

var (
	file_proto_random_number_gen_v1_service_proto_rawDescOnce sync.Once
	file_proto_random_number_gen_v1_service_proto_rawDescData []byte
)

func file_proto_random_number_gen_v1_service_proto_rawDescGZIP() []byte {
	file_proto_random_number_gen_v1_service_proto_rawDescOnce.Do(func() {
		file_proto_random_number_gen_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_random_number_gen_v1_service_proto_rawDesc), len(file_proto_random_number_gen_v1_service_proto_rawDesc)))
	})
	return file_proto_random_number_gen_v1_service_proto_rawDescData
}

var file_proto_random_number_gen_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_random_number_gen_v1_service_proto_goTypes = []any{
	(*GenerateIntRequest)(nil),  // 0: random_number_gen.GenerateIntRequest
	(*GenerateIntResponse)(nil), // 1: random_number_gen.GenerateIntResponse
}
var file_proto_random_number_gen_v1_service_proto_depIdxs = []int32{
	0, // 0: random_number_gen.RandomNumberGen.GenerateInt:input_type -> random_number_gen.GenerateIntRequest
	1, // 1: random_number_gen.RandomNumberGen.GenerateInt:output_type -> random_number_gen.GenerateIntResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_random_number_gen_v1_service_proto_init() }
func file_proto_random_number_gen_v1_service_proto_init() {
	if File_proto_random_number_gen_v1_service_proto != nil {
		return
	}
	file_proto_random_number_gen_v1_service_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_random_number_gen_v1_service_proto_rawDesc), len(file_proto_random_number_gen_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_random_number_gen_v1_service_proto_goTypes,
		DependencyIndexes: file_proto_random_number_gen_v1_service_proto_depIdxs,
		MessageInfos:      file_proto_random_number_gen_v1_service_proto_msgTypes,
	}.Build()
	File_proto_random_number_gen_v1_service_proto = out.File
	file_proto_random_number_gen_v1_service_proto_goTypes = nil
	file_proto_random_number_gen_v1_service_proto_depIdxs = nil
}
