// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.32.0
// source: proto/random-number-gen/v1/service.proto

package random_number_gen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RandomNumberGen_GenerateInt_FullMethodName = "/random_number_gen.RandomNumberGen/GenerateInt"
)

// RandomNumberGenClient is the client API for RandomNumberGen service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RandomNumberGenClient interface {
	GenerateInt(ctx context.Context, in *GenerateIntRequest, opts ...grpc.CallOption) (*GenerateIntResponse, error)
}

type randomNumberGenClient struct {
	cc grpc.ClientConnInterface
}

func NewRandomNumberGenClient(cc grpc.ClientConnInterface) RandomNumberGenClient {
	return &randomNumberGenClient{cc}
}

func (c *randomNumberGenClient) GenerateInt(ctx context.Context, in *GenerateIntRequest, opts ...grpc.CallOption) (*GenerateIntResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateIntResponse)
	err := c.cc.Invoke(ctx, RandomNumberGen_GenerateInt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RandomNumberGenServer is the server API for RandomNumberGen service.
// All implementations must embed UnimplementedRandomNumberGenServer
// for forward compatibility.
type RandomNumberGenServer interface {
	GenerateInt(context.Context, *GenerateIntRequest) (*GenerateIntResponse, error)
	mustEmbedUnimplementedRandomNumberGenServer()
}

// UnimplementedRandomNumberGenServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRandomNumberGenServer struct{}

func (UnimplementedRandomNumberGenServer) GenerateInt(context.Context, *GenerateIntRequest) (*GenerateIntResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateInt not implemented")
}
func (UnimplementedRandomNumberGenServer) mustEmbedUnimplementedRandomNumberGenServer() {}
func (UnimplementedRandomNumberGenServer) testEmbeddedByValue()                         {}

// UnsafeRandomNumberGenServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RandomNumberGenServer will
// result in compilation errors.
type UnsafeRandomNumberGenServer interface {
	mustEmbedUnimplementedRandomNumberGenServer()
}

func RegisterRandomNumberGenServer(s grpc.ServiceRegistrar, srv RandomNumberGenServer) {
	// If the following call panics, it indicates UnimplementedRandomNumberGenServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RandomNumberGen_ServiceDesc, srv)
}

func _RandomNumberGen_GenerateInt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateIntRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RandomNumberGenServer).GenerateInt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RandomNumberGen_GenerateInt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RandomNumberGenServer).GenerateInt(ctx, req.(*GenerateIntRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RandomNumberGen_ServiceDesc is the grpc.ServiceDesc for RandomNumberGen service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RandomNumberGen_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "random_number_gen.RandomNumberGen",
	HandlerType: (*RandomNumberGenServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateInt",
			Handler:    _RandomNumberGen_GenerateInt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/random-number-gen/v1/service.proto",
}
